# # .pre-commit-config.yaml
# repos:
# -   repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v4.6.0
#     hooks:
#     -   id: trailing-whitespace # Mandatory hook
#     -   id: end-of-file-fixer  # Mandatory hook
#     -   id: check-yaml
#     -   id: check-added-large-files

# -   repo: https://github.com/astral-sh/ruff-pre-commit
#     rev: v0.4.8
#     hooks:
#     -   id: ruff          # Linter
#         args: [--fix]
#     -   id: ruff-format   # Formatter (replaces black)

# -   repo: https://github.com/Yelp/detect-secrets
#     rev: v1.5.0
#     hooks:
#     -   id: detect-secrets # Mandatory hook

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.4.0
  hooks:
    - id: detect-secrets
- repo: https://github.com/psf/black
  rev: 24.8.0
  hooks:
    - id: black
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks:
    - id: ruff
