services:
  backend:
    build:
      context: .
      dockerfile: dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./requirements.txt:/app/requirements.txt
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - S3_BUCKET=${S3_BUCKET}

  frontend:
    build:
      context: ./src/frontend
      dockerfile: dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend:/app

  mlflow:
    build:
      context: .
      dockerfile: dockerfile.mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_INSECURE_HTTP=true
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./mlruns:/app/mlruns
      - ./mlflow.db:/app/mlflow.db

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=$GRAFANA_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD=$GRAFANA_ADMIN_PASSWORD

  evidently:
    build:
      context: .       # root directory
      dockerfile: src/app/monitoring/dockerfile.evidently
    container_name: evidently
    ports:
      - "7000:7000"
